### ISSUE TITLE
[BUG] [Goblin Retreat] OpenSea link to view Resale items opens in the same browser tab

### ISSUE THREAD

**Issue by johannesunana** [sunflower-land/sunflower-land#1907]
## Summary of Bug

Clicking the **View Items on Open Sea** button on Resale in Goblin Retreat opens the **OpenSea Sunflower Land Collectibles** webpage in the same tab.

## Steps to Reproduce

1. Open Sunflower Land. Click the boat to travel to Goblin Retreat.
2. Click Resale and wait for the popup to appear.
3. Click the **View Items on Open Sea** button.
4. Browser goes to https://opensea.io/collection/sunflower-land-collectibles in the same tab.

## Expected Behavior

The link to **OpenSea Sunflower Land Collectibles** in Resale should open in a new browser tab. Similar to **Go to Bumpkins.io** in Wearables.

## Actual Behavior

**OpenSea Sunflower Land Collectibles** opens in the same tab. The player leaves the Sunflower Land domain, requiring players to reconnect their wallet to re-access their farm.

## Screenshots/Recording

![Resale Goblin Retreat](https://user-images.githubusercontent.com/99703415/208667315-d98ca0a0-b8d6-4912-b9c2-e0db16701a48.png)

https://user-images.githubusercontent.com/99703415/208668345-87b3eccf-db0f-4fde-af81-5a168191f2c1.mp4

**Device Information:**

- Device: ASUS VivoBook 15
- OS: Windows 10 Version 22H2 (Build 19045.2364)
- Browser/App: Google Chrome
- Version: 108.0.5359.125 (Official Build) (64-bit)

**Comment by Polysemouse** [comment]
This is fixed by https://github.com/sunflower-land/sunflower-land/pull/1871

**Comment by johannesunana** [comment]
Hello @hujikol is this bug part of your fix? I did a hard refresh after Adam made two merges earlier today, and the bug is still there. Thanks.

**Comment by hujikol** [comment]
Yes it is also included in my pr here #1871 , it was merged but not yet live/ released to the game
